/*INSERT INTO CATEGORII*/

INSERT INTO CATEGORII (ID_PARINTE, DENUMIRE) SELECT NULL, 'Femei' FROM 
dual WHERE NOT EXISTS (SELECT 1 FROM CATEGORII WHERE DENUMIRE='Femei'); 
INSERT INTO CATEGORII (ID_PARINTE, DENUMIRE) SELECT NULL, 'Barbati' FROM 
dual WHERE NOT EXISTS (SELECT 1 FROM CATEGORII WHERE 
DENUMIRE='Barbati'); 
INSERT INTO CATEGORII (ID_PARINTE, DENUMIRE) SELECT NULL, 'Copii' FROM 
dual WHERE NOT EXISTS (SELECT 1 FROM CATEGORII WHERE DENUMIRE='Copii'); 
INSERT INTO CATEGORII (ID_PARINTE, DENUMIRE) SELECT (SELECT 
ID_CATEGORIE FROM CATEGORII WHERE DENUMIRE='Femei'), 'Rochii' FROM dual 
WHERE NOT EXISTS (SELECT 1 FROM CATEGORII WHERE DENUMIRE='Rochii'); 
INSERT INTO CATEGORII (ID_PARINTE, DENUMIRE) SELECT (SELECT 
ID_CATEGORIE FROM CATEGORII WHERE DENUMIRE='Femei'), 'Bluze' FROM dual 
WHERE NOT EXISTS (SELECT 1 FROM CATEGORII WHERE DENUMIRE='Bluze'); 
INSERT INTO CATEGORII (ID_PARINTE, DENUMIRE) SELECT (SELECT 
ID_CATEGORIE FROM CATEGORII WHERE DENUMIRE='Femei'), 'Pantaloni_femei' 
FROM dual WHERE NOT EXISTS (SELECT 1 FROM CATEGORII WHERE 
DENUMIRE='Pantaloni_femei'); 
INSERT INTO CATEGORII (ID_PARINTE, DENUMIRE) SELECT (SELECT 
ID_CATEGORIE FROM CATEGORII WHERE DENUMIRE='Barbati'), 'Camasi' FROM dual 
WHERE NOT EXISTS (SELECT 1 FROM CATEGORII WHERE DENUMIRE='Camasi'); 
INSERT INTO CATEGORII (ID_PARINTE, DENUMIRE) SELECT (SELECT 
ID_CATEGORIE FROM CATEGORII WHERE DENUMIRE='Barbati'), 'Tricouri_barbati' 
FROM dual WHERE NOT EXISTS (SELECT 1 FROM CATEGORII WHERE 
DENUMIRE='Tricouri_barbati'); 
INSERT INTO CATEGORII (ID_PARINTE, DENUMIRE) SELECT (SELECT 
ID_CATEGORIE FROM CATEGORII WHERE DENUMIRE='Barbati'), 'Blugi' FROM dual 
WHERE NOT EXISTS (SELECT 1 FROM CATEGORII WHERE DENUMIRE='Blugi'); 
INSERT INTO CATEGORII (ID_PARINTE, DENUMIRE) SELECT (SELECT 
ID_CATEGORIE FROM CATEGORII WHERE DENUMIRE='Copii'), 'Fete' FROM dual 
WHERE NOT EXISTS (SELECT 1 FROM CATEGORII WHERE DENUMIRE='Fete'); 
INSERT INTO CATEGORII (ID_PARINTE, DENUMIRE) SELECT (SELECT 
ID_CATEGORIE FROM CATEGORII WHERE DENUMIRE='Copii'), 'Baieti' FROM dual 
WHERE NOT EXISTS (SELECT 1 FROM CATEGORII WHERE DENUMIRE='Baieti'); 
INSERT INTO CATEGORII (ID_PARINTE, DENUMIRE) SELECT (SELECT 
ID_CATEGORIE FROM CATEGORII WHERE DENUMIRE='Rochii'), 'Rochii_casual' FROM 
dual WHERE NOT EXISTS (SELECT 1 FROM CATEGORII WHERE 
DENUMIRE='Rochii_casual'); 
INSERT INTO CATEGORII (ID_PARINTE, DENUMIRE) SELECT (SELECT 
ID_CATEGORIE FROM CATEGORII WHERE DENUMIRE='Rochii'), 'Rochii_elegante' 
FROM dual WHERE NOT EXISTS (SELECT 1 FROM CATEGORII WHERE 
DENUMIRE='Rochii_elegante'); 
INSERT INTO CATEGORII (ID_PARINTE, DENUMIRE) SELECT (SELECT 
ID_CATEGORIE FROM CATEGORII WHERE DENUMIRE='Bluze'), 'Bluze_maneca_lunga' 
FROM dual WHERE NOT EXISTS (SELECT 1 FROM CATEGORII WHERE 
DENUMIRE='Bluze_maneca_lunga'); 
INSERT INTO CATEGORII (ID_PARINTE, DENUMIRE) SELECT (SELECT 
ID_CATEGORIE FROM CATEGORII WHERE DENUMIRE='Bluze'), 'Bluze_maneca_scurta' 
FROM dual WHERE NOT EXISTS (SELECT 1 FROM CATEGORII WHERE 
DENUMIRE='Bluze_maneca_scurta'); 
INSERT INTO CATEGORII (ID_PARINTE, DENUMIRE) SELECT (SELECT 
ID_CATEGORIE FROM CATEGORII WHERE DENUMIRE='Fete'), 'Rochii_fete' FROM dual 
WHERE NOT EXISTS (SELECT 1 FROM CATEGORII WHERE DENUMIRE='Rochii_fete'); 
INSERT INTO CATEGORII (ID_PARINTE, DENUMIRE) SELECT (SELECT 
ID_CATEGORIE FROM CATEGORII WHERE DENUMIRE='Baieti'), 'Treninguri_baieti' 
FROM dual WHERE NOT EXISTS (SELECT 1 FROM CATEGORII WHERE 
DENUMIRE='Treninguri_baieti'); 
COMMIT; 



/*INSERT INTO Clienti*/

INSERT INTO CLIENTI (NUME, PRENUME, EMAIL, TELEFON, ORAS, 
ADRESA) VALUES 
('DORCEA','ALESIA_MARIA','dorceaalesia24@stud.ase.ro','0724638440','București','Aleea_Ba
rajul_Dunarii'); 
INSERT INTO CLIENTI (NUME, PRENUME, EMAIL, TELEFON, ORAS, ADRESA) 
VALUES ('POPESCU','ANA','ana.popescu@gmail.com','0711111111','București','Str. Unirii nr. 
10'); 
INSERT INTO CLIENTI (NUME, PRENUME, EMAIL, TELEFON, ORAS, ADRESA) 
VALUES ('IONESCU','MARA','mara.ionescu@gmail.com','0722222222','Cluj-Napoca','Str. 
Memorandumului nr. 3'); 
INSERT INTO CLIENTI (NUME, PRENUME, EMAIL, TELEFON, ORAS, ADRESA) 
VALUES ('STAN','VLAD','vlad.stan@yahoo.com','0733333333','Iași','Bd. Independenței nr. 
15'); 
INSERT INTO CLIENTI (NUME, PRENUME, EMAIL, TELEFON, ORAS, ADRESA) 
VALUES ('DUMITRU','ALINA','alina.dumitru@gmail.com','0744444444','Timișoara','Str. Alba 
Iulia nr. 8'); 
INSERT INTO CLIENTI (NUME, PRENUME, EMAIL, TELEFON, ORAS, ADRESA) 
VALUES ('MARIN','ANDREI','andrei.marin@gmail.com','0755555555','Constanța','Str. Mircea 
cel Bătrân nr. 22'); 
INSERT INTO CLIENTI (NUME, PRENUME, EMAIL, TELEFON, ORAS, ADRESA) 
VALUES ('GEORGESCU','BIANCA','bianca.georgescu@gmail.com','0766666666','Brașov','Str. 
Republicii nr. 1'); 
INSERT INTO CLIENTI (NUME, PRENUME, EMAIL, TELEFON, ORAS, ADRESA) 
VALUES ('VASILE','RARES','rares.vasile@gmail.com','0777777777','Sibiu','Str. Nicolae 
Bălcescu nr. 5'); 
INSERT INTO CLIENTI (NUME, PRENUME, EMAIL, TELEFON, ORAS, ADRESA) 
VALUES ('RADU','ELENA','elena.radu@gmail.com','0788888888','Craiova','Str. Carol I nr. 
12'); 
INSERT INTO CLIENTI (NUME, PRENUME, EMAIL, TELEFON, ORAS, ADRESA) 
VALUES 
('PETRESCU','SEBASTIAN','sebastian.petrescu@gmail.com','0799999999','Oradea','Str. 
Decebal nr. 20'); 
COMMIT;

/*INSERT INTO Produse*/

INSERT INTO PRODUSE (ID_CATEGORIE, DENUMIRE, BRAND, DESCRIERE, ACTIV) 
SELECT ID_CATEGORIE, 'Rochie casual din bumbac', 'UrbanStyle', 'Rochie casual, bumbac 
100%.', 'Y' FROM CATEGORII WHERE DENUMIRE = 'Rochii_casual'; 
INSERT INTO PRODUSE (ID_CATEGORIE, DENUMIRE, BRAND, DESCRIERE, ACTIV) 
SELECT ID_CATEGORIE, 'Rochie eleganta satin', 'Elegance', 'Rochie de seara, satin.', 'Y' 
FROM CATEGORII WHERE DENUMIRE = 'Rochii_elegante'; 
INSERT INTO PRODUSE (ID_CATEGORIE, DENUMIRE, BRAND, DESCRIERE, ACTIV) 
SELECT ID_CATEGORIE, 'Bluza maneca lunga', 'BasicWear', 'Bluza lejera, maneca lunga.', 'Y' 
FROM CATEGORII WHERE DENUMIRE = 'Bluze_maneca_lunga'; 
INSERT INTO PRODUSE (ID_CATEGORIE, DENUMIRE, BRAND, DESCRIERE, ACTIV) 
SELECT ID_CATEGORIE, 'Bluza maneca scurta', 'BasicWear', 'Bluza lejera, maneca scurta.', 
'Y' FROM CATEGORII WHERE DENUMIRE = 'Bluze_maneca_scurta'; 
INSERT INTO PRODUSE (ID_CATEGORIE, DENUMIRE, BRAND, DESCRIERE, ACTIV) 
SELECT ID_CATEGORIE, 'Camasa slim fit', 'ClassicFit', 'Camasa barbati, croiala slim.', 'Y' 
FROM CATEGORII WHERE DENUMIRE = 'Camasi'; 
INSERT INTO PRODUSE (ID_CATEGORIE, DENUMIRE, BRAND, DESCRIERE, ACTIV) 
SELECT ID_CATEGORIE, 'Tricou basic alb', 'BasicWear', 'Tricou bumbac, croiala regular.', 'Y' 
FROM CATEGORII WHERE DENUMIRE = 'Tricouri_barbati'; 
INSERT INTO PRODUSE (ID_CATEGORIE, DENUMIRE, BRAND, DESCRIERE, ACTIV) 
SELECT ID_CATEGORIE, 'Tricou imprimat', 'PrintLab', 'Tricou cu imprimeu grafic.', 'Y' 
FROM CATEGORII WHERE DENUMIRE = 'Tricouri_barbati'; 
INSERT INTO PRODUSE (ID_CATEGORIE, DENUMIRE, BRAND, DESCRIERE, ACTIV) 
SELECT ID_CATEGORIE, 'Pantaloni office femei', 'OfficeLine', 'Pantaloni eleganti pentru 
birou.', 'Y' FROM CATEGORII WHERE DENUMIRE = 'Pantaloni_femei'; 
INSERT INTO PRODUSE (ID_CATEGORIE, DENUMIRE, BRAND, DESCRIERE, ACTIV) 
SELECT ID_CATEGORIE, 'Blugi regular', 'DenimCo', 'Blugi regular fit, denim rezistent.', 'Y' 
FROM CATEGORII WHERE DENUMIRE = 'Blugi'; 
INSERT INTO PRODUSE (ID_CATEGORIE, DENUMIRE, BRAND, DESCRIERE, ACTIV) 
SELECT ID_CATEGORIE, 'Rochie fete', 'KidsJoy', 'Rochie copii, material moale.', 'Y' FROM 
CATEGORII WHERE DENUMIRE = 'Rochii_fete'; 
COMMIT; 


/*INSERT INTO Variante_produs*/

INSERT INTO VARIANTE_PRODUS (ID_PRODUS, MARIME, CULOARE, 
COD_PRODUS_ALES, PRET_LISTA) SELECT ID_PRODUS, 'M', 'Rosu', 'RCB-M-ROS', 
149.99 FROM PRODUSE WHERE DENUMIRE = 'Rochie casual din bumbac'; 
INSERT INTO VARIANTE_PRODUS (ID_PRODUS, MARIME, CULOARE, 
COD_PRODUS_ALES, PRET_LISTA) SELECT ID_PRODUS, 'L', 'Albastru', 'RCB-L-ALB', 
149.99 FROM PRODUSE WHERE DENUMIRE = 'Rochie casual din bumbac'; 
INSERT INTO VARIANTE_PRODUS (ID_PRODUS, MARIME, CULOARE, 
COD_PRODUS_ALES, PRET_LISTA) SELECT ID_PRODUS, 'S', 'Negru', 'RES-S-NEG', 
299.99 FROM PRODUSE WHERE DENUMIRE = 'Rochie eleganta satin'; 
INSERT INTO VARIANTE_PRODUS (ID_PRODUS, MARIME, CULOARE, 
COD_PRODUS_ALES, PRET_LISTA) SELECT ID_PRODUS, 'M', 'Alb', 'BML-M-ALB', 
89.99 FROM PRODUSE WHERE DENUMIRE = 'Bluza maneca lunga'; 
INSERT INTO VARIANTE_PRODUS (ID_PRODUS, MARIME, CULOARE, 
COD_PRODUS_ALES, PRET_LISTA) SELECT ID_PRODUS, 'S', 'Verde', 'BMS-S-VER', 
69.99 FROM PRODUSE WHERE DENUMIRE = 'Bluza maneca scurta'; 
INSERT INTO VARIANTE_PRODUS (ID_PRODUS, MARIME, CULOARE, 
COD_PRODUS_ALES, PRET_LISTA) SELECT ID_PRODUS, 'M', 'Alb', 'CSF-M-ALB', 
129.99 FROM PRODUSE WHERE DENUMIRE = 'Camasa slim fit'; 
INSERT INTO VARIANTE_PRODUS (ID_PRODUS, MARIME, CULOARE, 
COD_PRODUS_ALES, PRET_LISTA) SELECT ID_PRODUS, 'L', 'Alb', 'TBA-L-ALB', 59.99 
FROM PRODUSE WHERE DENUMIRE = 'Tricou basic alb'; 
INSERT INTO VARIANTE_PRODUS (ID_PRODUS, MARIME, CULOARE, 
COD_PRODUS_ALES, PRET_LISTA) SELECT ID_PRODUS, 'M', 'Negru', 'TIM-M-NEG', 
79.99 FROM PRODUSE WHERE DENUMIRE = 'Tricou imprimat'; 
INSERT INTO VARIANTE_PRODUS (ID_PRODUS, MARIME, CULOARE, 
COD_PRODUS_ALES, PRET_LISTA) SELECT ID_PRODUS, '32', 'Albastru', 'BR-32-ALB', 
199.99 FROM PRODUSE WHERE DENUMIRE = 'Blugi regular'; 
INSERT INTO VARIANTE_PRODUS (ID_PRODUS, MARIME, CULOARE, 
COD_PRODUS_ALES, PRET_LISTA) SELECT ID_PRODUS, '116', 'Roz', 'RF-116-ROZ', 
119.99 FROM PRODUSE WHERE DENUMIRE = 'Rochie fete'; 
COMMIT; 

/*INSERT INTO Stocuri*/

INSERT INTO STOCURI (ID_VARIANTA, CANTITATE_DISPONIBILA, PRAG_MINIM) 
SELECT ID_VARIANTA, 25, 5 FROM VARIANTE_PRODUS WHERE 
COD_PRODUS_ALES = 'RCB-M-ROS'; 
INSERT INTO STOCURI (ID_VARIANTA, CANTITATE_DISPONIBILA, PRAG_MINIM) 
SELECT ID_VARIANTA, 18, 4 FROM VARIANTE_PRODUS WHERE 
COD_PRODUS_ALES = 'RCB-L-ALB'; 
INSERT INTO STOCURI (ID_VARIANTA, CANTITATE_DISPONIBILA, PRAG_MINIM) 
SELECT ID_VARIANTA, 8, 2 FROM VARIANTE_PRODUS WHERE 
COD_PRODUS_ALES = 'RES-S-NEG'; 
INSERT INTO STOCURI (ID_VARIANTA, CANTITATE_DISPONIBILA, PRAG_MINIM) 
SELECT ID_VARIANTA, 40, 10 FROM VARIANTE_PRODUS WHERE 
COD_PRODUS_ALES = 'BML-M-ALB'; 
INSERT INTO STOCURI (ID_VARIANTA, CANTITATE_DISPONIBILA, PRAG_MINIM) 
SELECT ID_VARIANTA, 35, 8 FROM VARIANTE_PRODUS WHERE 
COD_PRODUS_ALES = 'BMS-S-VER'; 
INSERT INTO STOCURI (ID_VARIANTA, CANTITATE_DISPONIBILA, PRAG_MINIM) 
SELECT ID_VARIANTA, 20, 5 FROM VARIANTE_PRODUS WHERE 
COD_PRODUS_ALES = 'CSF-M-ALB'; 
INSERT INTO STOCURI (ID_VARIANTA, CANTITATE_DISPONIBILA, PRAG_MINIM) 
SELECT ID_VARIANTA, 60, 12 FROM VARIANTE_PRODUS WHERE 
COD_PRODUS_ALES = 'TBA-L-ALB'; 
INSERT INTO STOCURI (ID_VARIANTA, CANTITATE_DISPONIBILA, PRAG_MINIM) 
SELECT ID_VARIANTA, 22, 6 FROM VARIANTE_PRODUS WHERE 
COD_PRODUS_ALES = 'TIM-M-NEG'; 
INSERT INTO STOCURI (ID_VARIANTA, CANTITATE_DISPONIBILA, PRAG_MINIM) 
SELECT ID_VARIANTA, 10, 3 FROM VARIANTE_PRODUS WHERE 
COD_PRODUS_ALES = 'BR-32-ALB'; 
INSERT INTO STOCURI (ID_VARIANTA, CANTITATE_DISPONIBILA, PRAG_MINIM) 
SELECT ID_VARIANTA, 28, 7 FROM VARIANTE_PRODUS WHERE 
COD_PRODUS_ALES = 'RF-116-ROZ'; 
COMMIT; 

/*INSERT INTO Comenzi*/

/* 1 */ INSERT INTO COMENZI (ID_CLIENT, DATA_COMANDA, STATUS_COMANDA, 
TOTAL_COMANDA, ADRESA_LIVRARE) SELECT ID_CLIENT, SYSDATE-9, 'PLATITA', 
149.99, 'București, Aleea Barajul Dunării' FROM CLIENTI WHERE 
EMAIL='dorceaalesia24@stud.ase.ro'; 
/* 2 */ INSERT INTO COMENZI (ID_CLIENT, DATA_COMANDA, STATUS_COMANDA, 
TOTAL_COMANDA, ADRESA_LIVRARE) SELECT ID_CLIENT, SYSDATE-8, 
'LIVRATA', 299.99, 'București, Str. Unirii nr. 10' FROM CLIENTI WHERE 
EMAIL='ana.popescu@gmail.com'; 
/* 3 */ INSERT INTO COMENZI (ID_CLIENT, DATA_COMANDA, STATUS_COMANDA, 
TOTAL_COMANDA, ADRESA_LIVRARE) SELECT ID_CLIENT, SYSDATE-7, 'PLATITA', 
129.99, 'Cluj-Napoca, Str. Memorandumului nr. 3' FROM CLIENTI WHERE 
EMAIL='mara.ionescu@gmail.com'; 
/* 4 */ INSERT INTO COMENZI (ID_CLIENT, DATA_COMANDA, STATUS_COMANDA, 
TOTAL_COMANDA, ADRESA_LIVRARE) SELECT ID_CLIENT, SYSDATE-6, 'NOUA', 0, 
'Iași, Bd. Independenței nr. 15' FROM CLIENTI WHERE EMAIL='vlad.stan@yahoo.com'; 
/* 5 */ INSERT INTO COMENZI (ID_CLIENT, DATA_COMANDA, STATUS_COMANDA, 
TOTAL_COMANDA, ADRESA_LIVRARE) SELECT ID_CLIENT, SYSDATE-5, 
'ANULATA', 0, 'Timișoara, Str. Alba Iulia nr. 8' FROM CLIENTI WHERE 
EMAIL='alina.dumitru@gmail.com'; 
/* 6 */ INSERT INTO COMENZI (ID_CLIENT, DATA_COMANDA, STATUS_COMANDA, 
TOTAL_COMANDA, ADRESA_LIVRARE) SELECT ID_CLIENT, SYSDATE-4, 'PLATITA', 
79.99, 'Constanța, Str. Mircea cel Bătrân nr. 22' FROM CLIENTI WHERE 
EMAIL='andrei.marin@gmail.com'; 
/* 7 */ INSERT INTO COMENZI (ID_CLIENT, DATA_COMANDA, STATUS_COMANDA, 
TOTAL_COMANDA, ADRESA_LIVRARE) SELECT ID_CLIENT, SYSDATE-3, 
'RETURNATA', 199.99, 'Brașov, Str. Republicii nr. 1' FROM CLIENTI WHERE 
EMAIL='bianca.georgescu@gmail.com'; 
/* 8 */ INSERT INTO COMENZI (ID_CLIENT, DATA_COMANDA, STATUS_COMANDA, 
TOTAL_COMANDA, ADRESA_LIVRARE) SELECT ID_CLIENT, SYSDATE-2, 
'LIVRATA', 59.99, 'Sibiu, Str. Nicolae Bălcescu nr. 5' FROM CLIENTI WHERE 
EMAIL='rares.vasile@gmail.com'; 
/* 9 */ INSERT INTO COMENZI (ID_CLIENT, DATA_COMANDA, STATUS_COMANDA, 
TOTAL_COMANDA, ADRESA_LIVRARE) SELECT ID_CLIENT, SYSDATE-1, 'PLATITA', 
149.99, 'Craiova, Str. Carol I nr. 12' FROM CLIENTI WHERE 
EMAIL='elena.radu@gmail.com'; 
/* 10 */ INSERT INTO COMENZI (ID_CLIENT, DATA_COMANDA, 
STATUS_COMANDA, TOTAL_COMANDA, ADRESA_LIVRARE) SELECT ID_CLIENT, 
SYSDATE, 'NOUA', 0, 'Oradea, Str. Decebal nr. 20' FROM CLIENTI WHERE 
EMAIL='sebastian.petrescu@gmail.com'; 
COMMIT;


/*INSERT INTO Plati*/

/* 1 */ INSERT INTO PLATI (ID_COMANDA, DATA_PLATA, METODA, SUMA, 
STATUS_PLATA) SELECT ID_COMANDA, SYSDATE-9, 'CARD', TOTAL_COMANDA, 
'CONFIRMATA' FROM COMENZI WHERE ID_COMANDA = 1; 
/* 2 */ INSERT INTO PLATI (ID_COMANDA, DATA_PLATA, METODA, SUMA, 
STATUS_PLATA) SELECT ID_COMANDA, SYSDATE-8, 'CARD', TOTAL_COMANDA, 
'CONFIRMATA' FROM COMENZI WHERE ID_COMANDA = 2; 
/* 3 */ INSERT INTO PLATI (ID_COMANDA, DATA_PLATA, METODA, SUMA, 
STATUS_PLATA) SELECT ID_COMANDA, SYSDATE-7, 'TRANSFER', 
TOTAL_COMANDA, 'CONFIRMATA' FROM COMENZI WHERE ID_COMANDA = 3; 
/* 4 */ INSERT INTO PLATI (ID_COMANDA, DATA_PLATA, METODA, SUMA, 
STATUS_PLATA) SELECT ID_COMANDA, SYSDATE-6, 'RAMBURS', 0, 'INITIATA' 
FROM COMENZI WHERE ID_COMANDA = 4; 
/* 5 */ INSERT INTO PLATI (ID_COMANDA, DATA_PLATA, METODA, SUMA, 
STATUS_PLATA) SELECT ID_COMANDA, SYSDATE-5, 'RAMBURS', 0, 'ESUATA' 
FROM COMENZI WHERE ID_COMANDA = 5; 
/* 6 */ INSERT INTO PLATI (ID_COMANDA, DATA_PLATA, METODA, SUMA, 
STATUS_PLATA) SELECT ID_COMANDA, SYSDATE-4, 'CARD', TOTAL_COMANDA, 
'CONFIRMATA' FROM COMENZI WHERE ID_COMANDA = 6; 
/* 7 */ INSERT INTO PLATI (ID_COMANDA, DATA_PLATA, METODA, SUMA, 
STATUS_PLATA) SELECT ID_COMANDA, SYSDATE-3, 'TRANSFER', 
TOTAL_COMANDA, 'REFUND' FROM COMENZI WHERE ID_COMANDA = 7; 
/* 8 */ INSERT INTO PLATI (ID_COMANDA, DATA_PLATA, METODA, SUMA, 
STATUS_PLATA) SELECT ID_COMANDA, SYSDATE-2, 'CARD', TOTAL_COMANDA, 
'CONFIRMATA' FROM COMENZI WHERE ID_COMANDA = 8; 
/* 9 */ INSERT INTO PLATI (ID_COMANDA, DATA_PLATA, METODA, SUMA, 
STATUS_PLATA) SELECT ID_COMANDA, SYSDATE-1, 'CARD', TOTAL_COMANDA, 
'CONFIRMATA' FROM COMENZI WHERE ID_COMANDA = 9; 
/* 10 */ INSERT INTO PLATI (ID_COMANDA, DATA_PLATA, METODA, SUMA, 
STATUS_PLATA) SELECT ID_COMANDA, SYSDATE, 'RAMBURS', 0, 'INITIATA' FROM 
COMENZI WHERE ID_COMANDA = 10; 
COMMIT;
